-- Esquema de base de datos para FiguMatch (Supabase)

-- 1. Tablas de Ubicación y Escuelas (Diccionarios)
CREATE TABLE public.provincias (
  id serial PRIMARY KEY,
  nombre text NOT NULL
);

CREATE TABLE public.departamentos (
  id serial PRIMARY KEY,
  nombre text NOT NULL
);

CREATE TABLE public.localidades (
  id serial PRIMARY KEY,
  nombre text NOT NULL
);

CREATE TABLE public.escuelas (
  id serial PRIMARY KEY,
  nombre text NOT NULL
);

-- 2. Tabla de Perfiles
CREATE TABLE public.perfiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  id_publico text UNIQUE NOT NULL,
  nombre text NOT NULL,
  email text,
  avatar_url text,
  provincia_id integer REFERENCES public.provincias(id),
  departamento_id integer REFERENCES public.departamentos(id),
  localidad_id integer REFERENCES public.localidades(id),
  escuela_id integer REFERENCES public.escuelas(id),
  completitud integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Colecciones (Figuritas de cada usuario)
CREATE TABLE public.colecciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id uuid REFERENCES public.perfiles(id) ON DELETE CASCADE,
  sticker_id text NOT NULL,
  cantidad integer DEFAULT 1,
  UNIQUE(perfil_id, sticker_id)
);

-- Habilitar Realtime para colecciones
ALTER PUBLICATION supabase_realtime ADD TABLE colecciones;

-- 4. Tabla de Amistades (Red de coleccionistas)
CREATE TABLE public.amistades (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  solicitante_id uuid REFERENCES public.perfiles(id) ON DELETE CASCADE,
  receptor_id uuid REFERENCES public.perfiles(id) ON DELETE CASCADE,
  estado text DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aceptada', 'rechazada')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(solicitante_id, receptor_id)
);

-- Habilitar Realtime para amistades
ALTER PUBLICATION supabase_realtime ADD TABLE amistades;

-- 5. Tabla de Propuestas (Intercambios)
CREATE TABLE public.propuestas (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  solicitante_id uuid REFERENCES public.perfiles(id) ON DELETE CASCADE,
  receptor_id uuid REFERENCES public.perfiles(id) ON DELETE CASCADE,
  ofrecemos jsonb NOT NULL,
  pedimos jsonb NOT NULL,
  estado text DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aceptado', 'rechazado', 'cancelado')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Realtime para propuestas
ALTER PUBLICATION supabase_realtime ADD TABLE propuestas;
